### ISSUE TITLE
Can't find code of illustratioin in github

### ISSUE THREAD

**Issue by yanyu0517** [cliveharber/gettingMean-2#1]
I've been reading chapter 8.  After cloning the code and checkout into branch of `chapter-08`,  there is only a piece of code in the book. Some file like `app.component.ts`, `app.component.html` can't be found.

I found another repository [getting-MEAN-2](https://github.com/simonholmes/getting-MEAN-2), The code in this repo are seems to be the same with the book.

**Comment by cliveharber** [comment]
Thanks - I'll check to see if there's an issue

**Comment by cliveharber** [comment]
There is no issue - In Chapter 8, section 8.2.1, under the title "Making it the default component", the app.component.* files are no longer needed and are removed.
