### ISSUE TITLE
NODE_ENV if statement in section 5.5.3 not in chapter-05 branch

### ISSUE THREAD

**Issue by katurian** [cliveharber/gettingMean-2#10]
Hey Clive, I'm looking at the page I've copied below.

--

The database connection for your application is held in the db.js file in app_
server/models. The connection portion of this file currently looks like this:

```
const dbURI = 'mongodb://localhost/Loc8r';
mongoose.connect(dbURI);
```
Changing the value of dbURI based on the current environment is as simple as using an if statement to check NODE_ENV. The next code snippet shows how you can do this to pass in your live MongoDB connection. Remember to use your own MongoDB connection string rather than the one in this example:

```
let dbURI = 'mongodb://localhost/Loc8r';
if (process.env.NODE_ENV === 'production') {
dbURI =
'mongodb://heroku_t0zs37gc:1k3t3pgo8sb5enosk314gj@ds159330.mlab.com:5933
➥ 0/ heroku_t0zs37gc';
}
mongoose.connect(dbURI);
```
--
This is confusing me, because the code in the chapter-05 branch of `db.js` looks different:

```
const mongoose = require('mongoose');
const host = process.env.DB_HOST || '127.0.0.1'
const dbURL = `mongodb://${host}/Loc8r`;
const readLine = require('readline');

const connect = () => {
  setTimeout(() => mongoose.connect(dbURL, { useNewUrlParser: true, useCreateIndex: true, useUnifiedTopology: true}), 1000);
}
```
Which one am I supposed to go off of? When I run `heroku logs` after creating a heroku app with MLab and pushing chapter-05 to it, I receive the following error message:

```
2020-08-03T20:31:05.681419+00:00 app[web.1]: name: 'MongoNetworkError',
2020-08-03T20:31:05.681419+00:00 app[web.1]: errorLabels: [Array],
2020-08-03T20:31:05.681420+00:00 app[web.1]: [Symbol(mongoErrorContextSymbol)]: {}
2020-08-03T20:31:05.681420+00:00 app[web.1]: }]
2020-08-03T20:31:05.681757+00:00 app[web.1]: (node:23) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
```
I am running Linux Mint.

**Comment by cliveharber** [comment]
Hi

The issue is that the connection string to MongoDB changed, but the book text is static. The repo is more correct. I think that in this case the problem is that you might be missing a DB_HOST environment variable in your heroku set up as it looks like its trying to connect to your localhost on start up.

The DB_HOST environment variable is the MLab connection string that is in the form:
```mongodb://<username>:<password>@<hostname>:<port>/<database>```

Thanks

**Comment by katurian** [comment]
Thank you for the quick reply.

So with nodemon, I was passing in the DB_HOST environment variable like this:
```
NODE_ENV=production MONGODB_URI=mongodb://heroku_XXX9plkj:aoneqjccr0ff5ugXXXqs7ea4h@ds15XX08.mlab.com:51108/heroku_2XXX9plkj nodemon
```
I would I set up Heroku to act like this? Do I need to edit the procfile?

**Comment by cliveharber** [comment]
I think that you need to change MONGODB_URI to DB_HOST in your nodemon.

The environment call in the repo code is looking for DB_HOST. Maybe something for me to look at.

Failing that you can add environment variables into heroku with the tool belt/CLI.

$ heroku config:set DB_HOST=mongodb://heroku_XXX9plkj:aoneqjccr0ff5ugXXXqs7ea4h@ds15XX08.mlab.com:51108/heroku_2XXX9plkj <mongodb://heroku_XXX9plkj:aoneqjccr0ff5ugXXXqs7ea4h@ds15XX08.mlab.com:51108/heroku_2XXX9plkj>

I hope that helps.

Clive Harber
CTO // DistortedThinking
e: clive@distortedthinking.co.uk
w: www.distortedthinking.agency
t: +44 7815 166434

**Comment by katurian** [comment]
Okay, so `DB_HOST` is being passed in correctly now. But when I run `NODE_ENV=production DB_HOST=mongodb://heroku_XXX9plkj:aoneqjccr0ff5ugXXXqs7ea4h@ds15XX08.mlab.com:51108/heroku_2XXX9plkj nodemon` I get the following error:

`MongoParseError: Unescaped slash in userinfo section`

I may be wrong, but if you pass in `mongodb://heroku_XXX9plkj:aoneqjccr0ff5ugXXXqs7ea4h@ds15XX08.mlab.com:51108/heroku_2XXX9plkj` as `DB_HOST` does this line in `db.js`:

``const dbURL = `mongodb://${host}/Loc8r`;``

set `dbURL` equal to `mongodb://mongodb://heroku_XXX9plkj:aoneqjccr0ff5ugXXXqs7ea4h@ds15XX08.mlab.com:51108/heroku_2XXX9plkj/Loc8r` unintentionally? Or am I just misunderstanding the code.

**Comment by cliveharber** [comment]
This actually looks like an error in the code in the repo. I'll update the repo to reflect. Thanks for checking my code.

**Comment by katurian** [comment]
Let me know if I can help. I want to make sure everything is working properly before I move on to the API sections. This is a great book by the way, it's surprisingly difficult to find a good backend tutorial these days because everything involving javascript is usually frontend.

**Comment by cliveharber** [comment]
If you could just go ahead and try the MongoDB deployment with the small change I published earlier this morning to ensure it works would be fantastic. I’m sure it’s right now but haven’t been able to test it.

Thanks again for this report. I’ll let the publisher know your thoughts on the book.

**Comment by katurian** [comment]
I replaced my `db.js` with your revised version, and ran `NODE_ENV=production DB_HOST=mongodb://heroku_20X9plkj:aoneqjccr0ffXXXXkehqs7ea4h@ds151108.mlab.com:51108/heroku_20w9plkj nodemon` again. Here is the error I received:

`error: MongoParseError: Unescaped slash in userinfo section`

Also, if I set `useNewUrlParser` to `false` the error is more specific:

`error: Error: Password contains an illegal unescaped character`

I think the issue is the `/`. I tried to use [this function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) to escape it, but I'm getting the same error.

**Comment by cliveharber** [comment]
Hi Kate

I’ve taken another look and returned the code to more closely resemble the book content. The issue was that the code was doing ‘mongodb://mongodb://...` <mongodb://mongodb//...%60> when running from the environment variable. I believe I have resolved it now.

Thanks for your patience.

Clive Harber
CTO // DistortedThinking
e: clive@distortedthinking.co.uk
w: www.distortedthinking.agency
t: +44 7815 166434

**Comment by katurian** [comment]
That did it, thank you!
