### ISSUE TITLE
Not able to run application in Docker

### ISSUE THREAD

**Issue by Harsh-Mindtree** [cliveharber/gettingMean-2#3]
I tried to run chapter-10 with docker. But it is giving following error:- 
`disconnected
error: MongoNetworkError: failed to connect to server [database:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND database database:27017]
(node:17) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [database:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND database database:27017]
    at Pool.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/topologies/server.js:431:11)
    at Pool.emit (events.js:182:13)
    at connect (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:557:14)
    at makeConnection (/usr/src/app/node_modules/mongodb-core/lib/connection/connect.js:39:11)
    at callback (/usr/src/app/node_modules/mongodb-core/lib/connection/connect.js:261:5)
    at Socket.err (/usr/src/app/node_modules/mongodb-core/lib/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Kindly help where we need to change it.

**Comment by cliveharber** [comment]
This looks like the MongoDB instance hasn't started. Please check that you have MongoDB running by using `mongo` against the docker container. If this returns a MongoDB prompt then your instance is not running on the standard MongoDB port. If there's no response then you will need to (re)start MongoDB which should be as simple as running `mongod --smallfiles` against the docker container, but does depend on your current set up.

**Comment by Harsh-Mindtree** [comment]
Thanks for the reply @cliveharber I am new to docker so for learning on how to use docker for the current app. I cloned your repository and used the command you mentioned. It stays on the same error screen for a long time. I tried several other solutions to but each time I think my MongoDB instance doesn't start.

**Comment by Harsh-Mindtree** [comment]
Running `docker run mongo:4.0.4-xenial` gives following logs

![Screenshot 2020-01-20 at 15 17 07](https://user-images.githubusercontent.com/14075067/72737756-1b75e380-3b98-11ea-844d-b409d13fb7d6.png)

**Comment by cliveharber** [comment]
That looks like its up and running (now anyways). Try again the app again. If there's still no joy, then I suspect that the port for MongoDB is also closed. You'll need to map port 27017 from your local to 27017 in the docker container.
