### ISSUE TITLE
Cannot find http://localhost:3000/build/runtime.ec2944dd8b20ec099bf3.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by vethanom** [cliveharber/gettingMean-2#5]
Hi @cliveharber ,

When I am running localhost:3000 using docker it shows error "http://localhost:3000/build/runtime.ec2944dd8b20ec099bf3.js net::ERR_ABORTED 404 (Not Found)" in console.

localhost:4200 Angular Works Fine 

 what should I do ??

Thanks

**Comment by cliveharber** [comment]
Hi

Could you post me the HTML that gets generated? I'm not convinced that it needs the '/build' part of the path, so I'd like to see what its generating.

Could you also send me the actual versions of Angular, Node and Express and the full error that your project is using. I like to make sure that they are consistent with the versions specified in the package.json file for this project.

Cheers

Clive

**Comment by vethanom** [comment]
@cliveharber ,

Please find details of my docker containers and errors:

**Express Container Details:**
![ExpressContainer](https://user-images.githubusercontent.com/49445312/75601459-63feb600-5ae1-11ea-876c-92860c38fd42.png)

**Angular Container Details:** 
![AngularContainer](https://user-images.githubusercontent.com/49445312/75601470-80025780-5ae1-11ea-8226-c812affc6c4f.png)

**Angular Build/Index.html Details:**
![AngularBuildIndexHTML](https://user-images.githubusercontent.com/49445312/75601476-8abcec80-5ae1-11ea-8894-f6e742fee966.png)

**Angular Running on https://localhost:4200:** 
![AngularRunningOnContainer4200](https://user-images.githubusercontent.com/49445312/75601490-ab854200-5ae1-11ea-9256-81124b8a18b5.png)

**Express Running on https://localhost:3000:** 
![ExpressRunningOnContainer3000](https://user-images.githubusercontent.com/49445312/75601501-c061d580-5ae1-11ea-9578-4007c7c43243.png)

**& Firefox is showing below errors:**
![FirefoxErrors](https://user-images.githubusercontent.com/49445312/75798226-49a43100-5d9c-11ea-8116-829bd5e36744.png)

@cliveharber : Please let me know if any other details are needed.

It works fine when I run in local environment, its only has issues when I run it using Docker.

Thanks

**Comment by cliveharber** [comment]
The issue is that the Docker container doesn't expose port 4200 for the Angular application, nor does it start it up which is an oversight on my part. I'll roll a fix in the next few days.

**Comment by vethanom** [comment]
@cliveharber : Thank You Sir :)

**Comment by Bazhanov-Ilya** [comment]
HI, I followed the book referring to your code and this chapter happened in chapter 10. Tell me the solution to the problem
![locator](https://user-images.githubusercontent.com/48070116/84706247-53296180-af65-11ea-90f1-b9e4f38416d4.jpg)

**Comment by Bazhanov-Ilya** [comment]
Hi, @cliveharber
I followed the book referring to your code and this chapter happened in chapter 10. Tell me the solution to the problem
![locator](https://user-images.githubusercontent.com/48070116/84706555-d480f400-af65-11ea-9a6b-06ba9fd8ccf3.jpg)

**Comment by cliveharber** [comment]
The text in the book puts the bootstrap.min.js asset in the path assets/javascripts/bootstrap.min.js. This error looks to be say that the browser is expecting the bootstrap.min.js file to be on the path assets/js/bootstrap.min.js. Check the references to this file in your index.html file and that this file exists on the expected path

**Comment by Bazhanov-Ilya** [comment]
I checked the location of the file and the path to it, after I tried to transfer the file to a new folder along the path assets / js / bootstrap.min.js and register this route in index.html, but nothing worked.
![image](https://user-images.githubusercontent.com/48070116/84715833-51b66400-af7a-11ea-90ca-382cd6f333d8.png)

**Comment by Bazhanov-Ilya** [comment]
@cliveharber,
Thank you, I fixed it, but the application did not start working normally (the home page does not work, authorization does not go to the details page), and the console does not give errors

**Comment by Bazhanov-Ilya** [comment]
@cliveharber
Thanks for the explanation, but I still can not understand why the application does not work after the correction. On the home page, only a list of the nearest establishments is visible, and when you go to the details page, the transition is not carried out
![image](https://user-images.githubusercontent.com/48070116/84804851-03ea3c00-b00c-11ea-8f30-fed071c141d5.png)

**Comment by Bazhanov-Ilya** [comment]
@cliveharber, I got errors in the console, could you help me with this.
![image](https://user-images.githubusercontent.com/48070116/84828986-a5cf5000-b02f-11ea-9b25-61be2f181df0.png)

**Comment by cliveharber** [comment]
Without seeing the code that you have, I'm not sure what the issue is. Is there somewhere you can put it so that I can see it?

**Comment by Bazhanov-Ilya** [comment]
@cliveharber, the code matches your code from chapter 12 with the changed route in index.html line 21 to <script src="assets/javascripts/bootstrap.min.js"></script>
when starting via npm start
![image](https://user-images.githubusercontent.com/48070116/84837278-62311200-b040-11ea-8080-0fe0f5b5772f.png)
when starting via ng serve
![image](https://user-images.githubusercontent.com/48070116/84837419-c3f17c00-b040-11ea-827e-e38a4ff561cc.png)

**Comment by cliveharber** [comment]
It looks like you're using MongoDB 4.2 or greater. In this version of the database, the API for $geoNear changed. This happened earlier this year, long after the book was published.

In app_api/controllers/locations.js, function locationsListByDistance needs to change slightly.

Change the geoOptions object to:

```
const geoOptions = {
    distanceField: 'distance.calculated',
    key: 'coords',
    spherical: true,
    maxDistance: 20000,
  }
```

and then change the Loc.aggregate function (~ line 22):
```
const results = await Loc.aggregate([
      {
        $geoNear: {
          near,
          ...geoOptions,
        },
      },
      { $limit: 10 },
    ])
```
This should get the maps working again.

**Comment by Bazhanov-Ilya** [comment]
@cliveharber, I use MongoDB 4.0.18, 
the console constantly gives 3 errors
![image](https://user-images.githubusercontent.com/48070116/84882950-a223e380-b098-11ea-86dd-0f835ca1b817.png)

**Comment by Bazhanov-Ilya** [comment]
I use MongoDB 4.0.18,
the console constantly gives 3 errors
[image: image.png]

ср, 17 июн. 2020 г. в 03:30, cliveharber <notifications@github.com>:
