### ISSUE TITLE
"$geoNear no longer supports the 'limit' parameter. Use a $limit stage instead."

### ISSUE THREAD

**Issue by bemau** [cliveharber/gettingMean-2#8]
Hello,
When I am running this API it shows the following error
`http://localhost:3000/api/locations?lng=-0.9690884&lat=51.455041&maxDistance=20000`
> "$geoNear no longer supports the 'limit' parameter. Use a $limit stage instead."
it worked like a charm as soon as removed the limit from the const geoOptions.

**Comment by cliveharber** [comment]
Thanks for letting me know. I believe that this is still available for the version of MongoDB that gets used with the book, but its good to make a note of.

**Comment by alienvelour** [comment]
If using later versions of MongoDB, you can remove `limit` from `geoOptions` and then add the `$limit` stage like this:

```
    const results = await Loc.aggregate([
      {
        $geoNear: {
          near,
          ...geoOptions,
        },
      },
      {
        $limit: 10,
      },
    ]);
```
